### PR TITLE
Better Date Filter

### LINKED ISSUE #70: Better date filter
Check the `StatsDashboard.tsx` page and the `filters/DateFilter.tsx` component to get an idea of how the filters are going to work. Essentially:
>  Each filter has...
>  - an id - a unique identifier for the filter used to remove or update it
> - a component that is displayed in the filter bar, displays the state of its filter, and can be clicked on to modify or remove the filter.
> - an operation - a function that takes an incident and returns a boolean. If the incident passes the filter, the function should return true.

You will need to make a new file, probably starting with a copy of  `filters/DateFilter.tsx`. You'll also need to add your component to the `filters/AddFilter.tsx` component's list so it can be used.

Your filter is based on **incident date**. The user should be able to choose a single date or range of dates, and incidents will only pass the operation if their date is on, before, or after the chosen single date, or between the chosen two dates.

Here are some UI ideas. I don't expect you to implement the calendar view unless you're feeling exceptionally motivated. 
<p>

</p>

Notion_dq86me14Ch

### PR DESCRIPTION
**Pull request by MysteryCoder456**
Addresses issue #70
- **feat: drop down menu to select date filter option**
- **feat: working date filtering (except between filter)**
- **feat: added second date input + made 'between' filter inclusive**

### CODE REVIEW

**Comment by MysteryCoder456** [comment]
Screenshots of what the new date filter looks like right now:


<br><br>

<br><br>

**Comment by the-snesler** [comment]
Looks great so far! Excited to see the end product :)

**Comment by the-snesler** [comment]
Also, a heads up-- if you create a branch instead of making a fork, you can get a preview URL of your pull request. It makes it a lot easier for everyone else to take a look at your work before it's merged. You'll notice that it was skipped for this PR:
firefox_LTZV3FrakK
I can show you how to do that this weekend :)

**Review by the-snesler — APPROVED** [review]
Looks great. I like the use of a second popup window for the different types of configurations!

**Pull request merged**
