### PR TITLE
Location filters

### LINKED ISSUE #27: Location-based filtering
Depends on #25 

Filter by country/ies, then based on selected country/ies, select department/province.

Department/province options should be calculated in the querying logic, as a new field on the `DB` type. They can be calculated by checking all incidents for possible.

### PR DESCRIPTION
**Pull request by the-snesler**
Allows filtering by country, department, and municipality(?). Closes #27

- [x] Move filter calculation to parent of Map
- [x] Show popup with list of countries
  - [x] Departments
- [x] Filter them based on the popup

firefox_dxpQh0MEdb

### CODE REVIEW

**Comment by TetraTsunami** [comment]
firefox_dxpQh0MEdb

**Review by JackBlake-zkq — APPROVED** [review]
Looks great Sam 👍

I resolved merge conflicts (was harder than expected 😤)

and made some miscellaneous changes like updating the text in the tooltips and moving a couple controls

**Comment by the-snesler** [comment]
Good catch on the tooltip translations. 
One consideration: if two or more \<Control\> elements are in the same corner of the map, the \<Control\> should be moved into the parent or else whenever one remounts it'll move itself to the first position. You can see that happening in the preview with the year selector and the search box. It's not a huge issue and a very easy fix though.
I would approve but I can't since it's my own PR :/

**Comment by JackBlake-zkq** [comment]
Good point, just made that fix 👍

**Review by JackBlake-zkq — APPROVED** [review]

**Pull request merged**
